### ISSUE TITLE
Grid

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/WebCoreStyleSheets#114]
# General Support Request

Auro has a layout concept that is supported by design tokens, but there is no official 'grid'. 
https://auro.alaskaair.com/layout/grid

## Support request

How can Auro best support a grid? 

## Possible Solution

The Auro team needs to consult with the design group to distill down what are the common needs between design and engineering. 

The content team will use this heavily in there new pages so use the templates that we've created to help determine what grid solution will accommodate those designs the best.

Bootstrap has a great grid solution that we can mimic. https://getbootstrap.com/docs/4.0/layout/grid/#sass-mixins
Explore the 2 and 3 column components we created in auroLabs as we currently use these on content pages.

## Additional context

While this issue is created in the WCSS repo, there is nothing stating that the solution needs to be in WCSS. In the review of this, I want to explore all possible options for how we can best create a grid layout solution. 

This also should take into account the work that the content team is doing around pre-structured layout templates. 

## Acceptance Criteria
We need to have an opinion on how rows and columns will work.  
We need a two column layout with opinions on how these should be set. (1/3 and 2/3 and equal width any other recommended layouts for a 2 col?)
We need a three column layout with opinions on what options we should support. (Will they always be equal width or do we want to support alternatives )
We need a four column layout, same questions as above.
In some cases content will be injected in a column and we won't have control over the number of items that are added.
For example if we have a 4 column layout and a 5th item is added the assumption is that it will go on a new row but does the item take up the entire row or does it stay at a certain width that is determined in layout.

**Comment by leeejune** [comment]
Is "official grid" referring to a standard grid that all designers are recommended to follow?

**Comment by blackfalcon** [comment]
Yes. As well as a code solution that engineers can follow. Please schedule some time with me to go into the details on this and where I see an opportunity.

**Comment by leeejune** [comment]
Will be reaching out to Erika when developing the Grid. Refer to Design Fair comments for short dicussion.

**Comment by blackfalcon** [comment]
I feel that there has been more discussion on this versus execution. Adding this to the 4.1 milestone.

**Comment by shonore-aa** [comment]
I am working on a generic responsive 12 column grid system in the flightsearch-lem-svelte repo! I would be happy to share with anyone who is interested

**Comment by leeejune** [comment]
Link to 4 col grid system: https://www.figma.com/file/FvUT8KhQ3xBGLM5JFz7awf/Grid-System?node-id=0%3A1

**Comment by blackfalcon** [comment]
@leeejune looking at the Figma, I am seeing a lot of very specific references to pixel sizes in the grid blocks. Is this an example reference or designed to be a specification?

**Comment by leeejune** [comment]
It is meant to be "min-width" specs. @braven112 can probably better explain!

**Comment by blackfalcon** [comment]
STANDUP: Initial work has been completed. Moving issue to REVIEW for @braven112 review.

**Comment by blackfalcon** [comment]
I am not sure how this happened, but just a reminder. Please DO NOT manually move an issue to `DONE`. Please `CLOSE` the issue and this will automatically move the status to `DONE`.
