### ISSUE TITLE
UL and OL styling options

### ISSUE THREAD

**Issue by braven112** [AlaskaAirlines/WebCoreStyleSheets#115]
Request from content producers to make this consistent.  We'll need to investigate if their is already a way to do this or if a new class needs to be created for it.

https://dev.azure.com/itsals/E_Retain_Content/_backlogs/backlog/E_Retain_Content%20Team/Stories/?showParents=true&workitem=753208

**Comment by blackfalcon** [comment]
It was determined way back when that most teams already had support for correcting this issue within their project. 

This would be an opt-in use case. Either we add this to essentials with a class like we did with `fineprint` or we make a standalone Sass import. 

Is there a design standard for this that we can code to?

**Comment by braven112** [comment]
> Is there a design standard for this that we can code to?

Not yet, I'll be working with Jeanie and @leeejune.  I was thinking some sort of optional class like `fineprint` as well.

**Comment by blackfalcon** [comment]
@ jrbromberg executed the linked PR.
