### ISSUE TITLE
Docsite anchor links with commas in the anchor are broken

### ISSUE THREAD

**Issue by Eliza-Huang** [AlaskaAirlines/WebCoreStyleSheets#119]
## Describe the bug
Any anchor in the doc site with a comma in it (ie. `#normalize-css-#{$scope}button,#{$scope}input`) does not work, it will do nothing.

## To Reproduce
1. Go to `https://alaskaairlines.github.io/WebCoreStyleSheets`
2. Scroll down on the side nav until a nav link with a comma in it appears
3. Click on it
4. Notice that the page does not jump to the anchor and instead, nothing happens 

or 

1. Go to `https://alaskaairlines.github.io/WebCoreStyleSheets/#normalize-css-#{$scope}button,#{$scope}input`
2. Notice that you are taken to the top of the page and not to the anchor

## Expected behavior
When using an anchor link with a comma in the anchor, the page will jump to the appropriate anchor on the page.

## Desktop (please complete the following information):
 - OS: iOS
 - Browser tested on Chrome & Safari
 - Version 105.0.5195.52 (Official Build) (arm64) - Chrome

## Smartphone (please complete the following information):
N/A - did not test

**Comment by blackfalcon** [comment]
Sorry, while I agree that this is a pain, this is an issue with the [SassDoc](http://sassdoc.com/) that is used to generate the site and not something I can easily address. Also, this project hasn't been updated in almost 3 years. 

FYI, one of our directives over 2023 and 2024 is to remove our dependency on Sass and take better advantage of CSS in named template literals within LitElement. https://twitter.com/daKmoR/status/1191347381700321281
