### ISSUE TITLE
Grid design specs

### ISSUE THREAD

**Issue by leeejune** [AlaskaAirlines/WebCoreStyleSheets#127]
# General Support Request

There was a lot of work behind grids (new breakpoints, new columns, responsive grids, dynamic spacing), but no centralized documentation. The goal is to bring these together and outline specs in documentation.

## Context
[Grid](https://www.figma.com/file/TKB51n5UsydIZT5oHS8thA/Layout?node-id=41%3A306)
[Dynamic spacing](https://www.figma.com/file/TKB51n5UsydIZT5oHS8thA/Layout?node-id=148%3A326)
[Responsive grids](https://www.figma.com/file/FvUT8KhQ3xBGLM5JFz7awf/Grid-System?node-id=0%3A1)

**Comment by leeejune** [comment]
Grid documentation is in progress. Will be needing to add guidelines for dynamic spacing and responsive grids as well. This will be added into the Auro toolkit Figma file.

**Comment by leeejune** [comment]
Updated grid: https://www.figma.com/file/XLcJtsRkYA2fIIky7xVyyb/grid-diagram?node-id=5285%3A15841&t=j8PwaHLpFEflnZeI-4

**Comment by leeejune** [comment]
Documentation for dynamic spacing and grids have been added to the Auro toolkit Figma file. Next things we need are prioritization of the development of new breakpoints ([outlined here](https://www.figma.com/file/XLcJtsRkYA2fIIky7xVyyb/grid-diagram?node-id=5285%3A15841&t=j8PwaHLpFEflnZeI-4)). Once that is complete, we can update the grid documentation on Figma as well.

**Comment by blackfalcon** [comment]
Is there a link between this issue and this one? 

- https://github.com/AlaskaAirlines/WebCoreStyleSheets/issues/129

**Comment by leeejune** [comment]
@blackfalcon Somewhat.. need @braven112's insight on this.

**Comment by braven112** [comment]
Looks like this is the same as this one https://github.com/AlaskaAirlines/AuroDocsSite/issues/118
