### ISSUE TITLE
New 1 column page layout.

### ISSUE THREAD

**Issue by braven112** [AlaskaAirlines/WebCoreStyleSheets#129]
# User story

As a designer or engineer I want to have a one column standard page layout available to use so that I can use the new auro breakpoints and have consistent page sizes across products.

Here is the user story the content team is working on:
https://dev.azure.com/itsals/E_Retain_Content/_boards/board/t/E_Retain_Content%20Team/Stories/?workitem=853679

## Definition of “Done” (exit criteria)

- [ ] The new layout uses the dynamic spacing tokens
- [ ] Setup a quick call with Jason, Dale or Jordan on how to use the doc site.
- [ ] Make a class in WCSS that handles the max-width and padding for a 1 column layout.
- [ ] New layout class has been added to WCSS
- [ ] An example on the Auro doc site of a 1 column page layout using our new grid tokens (sync with June on how/where to display this)
- [ ] Integrate common components that would be often used 1 page layouts like auro-nav - breadcrumbs, auro-header along with lorem ipsum text.

**Comment by blackfalcon** [comment]
@braven112  The team needs to have more discussion on what the work for this actually is. 

- Is there a design spec? What is the new layout? 
- What is the assumption of selectors to be added to WCSS? 
- What are 'the dynamic spacing tokens'?

**Comment by blackfalcon** [comment]
@leeejune will schedule meeting with @blackfalcon to understand how to move forward with this request.
