### ISSUE TITLE
New 2 column page layout (Side Nav Template)

### ISSUE THREAD

**Issue by leeejune** [AlaskaAirlines/WebCoreStyleSheets#130]
# User story

As a designer or engineer, I want to be able to have a standard 2 column layout with a side navigation, so I can easily insert content and maintain consistent layouts across other pages.

Here is the user story the content team is working on:
https://dev.azure.com/itsals/E_Retain_Content/_backlogs/backlog/E_Retain_Content%20Team/Stories/?showParents=true&workitem=853681

## Outline subtasks or tasks

> List specific steps required to deliver this work.

- [ ] Document 2 column layout in Figma
- [ ] Document 2 column layout options for devs
- [ ] Implement left navigation

## Definition of “Done” (exit criteria)

- [ ] The new layout uses the dynamic spacing tokens
- [ ] Setup a quick call with Jason, Dale or Jordan on how to use the doc site.
- [ ] Make a class in WCSS that handles the max-width and padding and mobile layout for a 2 column layout.
- [ ] New layout class has been added to WCSS
- [ ] An example on the Auro doc site of a 2 column page layout using our new grid tokens (sync with June on how/where to display this)
- [ ] Integrate common components that would be often used 1 page layouts like auro-nav - breadcrumbs, auro-sidenav, auro-header along with lorem ipsum text.
- [ ] The documented design spec has been created
- [ ] Assets and instructions are available in Figma
- [ ] New layout has been added to WCSS

**Comment by blackfalcon** [comment]
Updating to `design` work, punting the issue to be refined once @leeejune is back to help with the definition of work for this issue.
