### ISSUE TITLE
Transparent Border in Style Sheets

### ISSUE THREAD

**Issue by isaiahscheel** [AlaskaAirlines/WebCoreStyleSheets#139]
I found a transparent border set for the focus state coming in the styles. This is causing our flight search microsite to not have a focus state on tab for things that do not have one defined like the footer. 

In ascom: 

![image](https://user-images.githubusercontent.com/40191651/209195781-ac59d1c8-caa1-4d31-a80c-6c543a19b88e.png)

![image](https://user-images.githubusercontent.com/40191651/209195823-099bf56c-7c29-416d-872e-66571828048a.png)

On our microsite: 

![image](https://user-images.githubusercontent.com/40191651/209195975-2c1f3446-b958-4fac-a210-588895bfe1da.png)

![image](https://user-images.githubusercontent.com/40191651/209196007-2d08cb40-ccbb-4fb6-8902-274a21ef9d20.png)

Found this:
https://github.com/AlaskaAirlines/WebCoreStyleSheets/blob/9a2d7a411bed8443a94cd2ed601e53f689b6738a/src/_core.scss#L84

In dev tools:
![image](https://user-images.githubusercontent.com/40191651/209196312-3b67bf2e-e21d-487b-b00b-71875998b13b.png)

If I override this in dev tools it seems to work fine but I can't get it to work via code.

I am not 100% sure that this is a "bug" but maybe some guidance is needed on how to overwrite this attribute on our microsite.

Thank you!

**Comment by blackfalcon** [comment]
This issue got lost in the mix. Looking at the production site, I am not sure if this is still an issue? When tabbing through this UI, the `focus-visible` interaction is working as expected. 

@isaiahscheel can you verify if this is still an issue to pursue?
