### ISSUE TITLE
Fonts not getting proper spacing when using Iphones

### ISSUE THREAD

**Issue by jesussilverioea** [AlaskaAirlines/WebCoreStyleSheets#142]
## Describe the bug

There is an issue with Iphones and the `<b>` adding some spacing on the Iphones

opening from iphone:

![image](https://user-images.githubusercontent.com/108018885/211632551-1516740d-60c1-4544-b30c-7e6aff091f91.png)

after investigation it seems to be an auro issue when the font is BOLD on iphone browsers.

auro site from iphone:

![image](https://user-images.githubusercontent.com/108018885/211632580-5f70d469-bb26-4638-a9ae-acaf372e1e24.png)

we could create an auro issue since it seems to be a bug with the fonts and IOS browsers:
https://stackoverflow.com/questions/28833958/why-is-ios-safari-adding-extra-letter-spacing#:~:text=I%20found%20the%20solution%20in%20this%20question

## Expected behavior

It should not add spaced in between the letters when using the `<b>` tag

**Comment by jesussilverioea** [comment]
Was this issue brought up by a designer or have you consulted with a designer regarding this issue?
     - Yes. It was brought up by our designer when testing mobile version of the component.

**Comment by blackfalcon** [comment]
@leeejune please bring this up with the design team to evaluate the impact of this potential issue. 

If this is considered an issue to address, the suggested path is to another value into the font-weight ladder. Currently, we support `100`, `300` and `500`. 

#### In WebCoreStyleshets 

https://github.com/AlaskaAirlines/WebCoreStyleSheets/blob/master/src/_fonts.scss

#### In design tokens 

https://github.com/AlaskaAirlines/AuroDesignTokens/blob/d857b3f286964a682c209cbacab82128f55207d2/src/text.json#L19-L36

**Comment by leeejune** [comment]
The solution we currently have will involve buying more font packages which will cost a lot of money... I talked to Tom about it and I don't think we have a strong enough case to make the purchase.
