### ISSUE TITLE
Cannot import tokens/essentials

### ISSUE THREAD

**Issue by ArcherScript** [AlaskaAirlines/WebCoreStyleSheets#189]
### Please verify the version of auro-wcss you have installed

5.1.0

### Please describe the bug

1. Create project
2. Add `@import '@aurodesignsystem/webcorestylesheets/src/tokens/essentials';` to .scss / .sass file
3. See error

```
Error: Can't find stylesheet to import.
  ╷
8 │ @import '@aurodesignsystem/webcorestylesheets/src/tokens/essentials';
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

### Reproducing the error

None

### Expected behavior

Essentials should be importable as per the documentation

### Additional context

Tried in a brand new project as well as an existing project

### Exit criteria

Update documentation to not include essentials OR fix the essentials import error

**Comment by ArcherScript** [comment]
Same issue for focus-visible
@import '@aurodesignsystem/webcorestylesheets/src/tokens/focus-visible';

**Comment by Patrick-Daly-AA** [comment]
Looks like our documentation is out of date.  Will investigate and update.

**Comment by blackfalcon** [comment]
This content was updated with a recent BETA update. This will be released to the public once the BETA has completed its development cycle. 

https://github.com/AlaskaAirlines/WebCoreStyleSheets/pull/196/files
