### ISSUE TITLE
Unnecessary tilde in import in documentation

### ISSUE THREAD

**Issue by ArcherScript** [AlaskaAirlines/WebCoreStyleSheets#190]
### Please verify the version of auro-wcss you have installed

4.3.1

### Please describe the bug

1. Attempt to import with tilde
2. See outputted error
3. Remove tilde
4. See successful import

### Reproducing the error

None

### Expected behavior

Documentation should just use a regular import statement:
`@import '~@aurodesignsystem/webcorestylesheets/src/breakpoints';`
should just be
`@import '@aurodesignsystem/webcorestylesheets/src/breakpoints';`

### Additional context

I don't think anyone using a modern bundler is going to have to reference node_modules via a ~. It will actually output an error in some scenarios where your project does not support / allow ~ imports.

### Exit criteria

Documentation is updated or clarified

**Comment by blackfalcon** [comment]
Hi @ArcherScript, 

Thank you for raising this issue and we are sorry that you ran into problems with the directions. 

As for your statement that no modern bundler would reference the node_modules using the `~` is not 100% accurate. Using the `~` [was part of the Webpack Sass loader API](https://github.com/webpack-contrib/sass-loader?tab=readme-ov-file#resolving-import-at-rules), although it is now deprecated. We just haven't updated the docs yet. 

I recommend the following: 

1. Remove the references to the `~` in the docs
2. Place more emphasis on the pre-processed CSS assets over the Sass use
3. Update the Sass imports documentation to be more agnostic of front-end platform.
