### ISSUE TITLE
Unsafe removal of focus outline

### ISSUE THREAD

**Issue by littleninja** [AlaskaAirlines/WebCoreStyleSheets#47]
Hello!

I noted the `@deprecated` comments, looking to understand the expected behavior and path forward.

We import `@alaskaairux/orion-web-core-style-sheets/dist/baseline';` but hadn't yet imported the peer dependency `focus-visible`. I noticed all focus outlines were removed from our `<button>` and `<a>` elements without a fallback and traced it back to these lines:

https://github.com/AlaskaAirlines/WebCoreStyleSheets/blob/bca4868df665279c32913235a450bc1cb35e526c/src/_baselineLTE.scss#L28-L30

Should it be revised to something like the defensive style in the polyfill docs?:

```css
.js-focus-visible :focus:not(.focus-visible) {
  outline: none;
}
```

I foresee a problem with the suggestion above because we import `baseline.scss` scoped to our page wrapper class. Or maybe this is a known issue and you have a suggestion for how to fix-forward. We're about to add the focus-visible polyfill but this is motivated from wanting to protect other consumers who aren't loading the polyfill from accidentally removing their a11y styles. Please let me know if I can clarify or help. Thank you!

**Comment by blackfalcon** [comment]
I see your point. The issue you are finding is that the initial opinion of WCSS was intended for Greenfield projects and this behavior was expected. The intent was that focus-visible would be the prevailing path forward. 

Given this new context, I see a path forward for Auro and the new essentials/core Sass files to correct this opinion. 

Thanks for your feedback.
