### ISSUE TITLE
Missing utility class selectors on docs site

### ISSUE THREAD

**Issue by geoffrich** [AlaskaAirlines/WebCoreStyleSheets#53]
## Describe the bug
.util_is-smOnly, .util_is-mdOnly, .util_is-mdOnly--inline, .util_is-mdAppears, .util_is-mdAppears--inline, .util_is-lgOnly, and .util_is-lgOnly--inline are all missing from [the docs site](https://alaskaairlines.github.io/WebCoreStyleSheets). They are, however, referenced in deprecation warnings (e.g. for[ .util_is-mobileOnly](https://alaskaairlines.github.io/WebCoreStyleSheets/#%E2%80%A0deprecated-css-.util_is-mobileOnly)).

This prevents devs with less familiarity with the design system from knowing what is available to them.

## Expected behavior
All WCSS selectors are present on the doc site.

## Screenshots
Only the deprecated breakpoint utility classes show in the sidebar:
![image](https://user-images.githubusercontent.com/4992896/88219159-0a289500-cc16-11ea-8975-4468384ba29f.png)

They are also missing from the search results:
![image](https://user-images.githubusercontent.com/4992896/88219213-1f9dbf00-cc16-11ea-8252-3a8c3ae42d29.png)

**Comment by blackfalcon** [comment]
Researching issue and looking for resolution.
