### ISSUE TITLE
Do not remove focus styles by default

### ISSUE THREAD

**Issue by geoffrich** [AlaskaAirlines/WebCoreStyleSheets#63]
## Is your feature request related to a problem? Please describe.
The default behavior when importing `essentials.css` is to remove focus styles from everything on the page. This makes it way too easy for devs to accidentally remove focus styles from elements that do not have a focus visible fallback. Most will not notice that the focus styles are missing, resulting in a major accessibility violation. 

See also AlaskaAirlines/auro-button#97, where focus styles do not properly apply to a custom element inside a shadow root. Because the focus visible polyfill did not load for the inner component, the focus styles inside the entire component are missing. If the default was to show focus styles and only remove them once focus visible was loaded, this issue would not have an a11y impact.

It is better for a page's design to be wrong (focus styles shown when not using the keyboard) than for a page to be inaccessible to keyboard users. Turning off all focus styles by default is an a11y footgun and should be changed.

It is better for focus styles to accidentally be shown than to accidentally be removed. The former means the visual design is incorrect, the latter means the page is inaccessible to keyboard users. Turning off all focus styles by default is an a11y footgun and should be changed.

## Describe the solution you'd like
We should not remove focus styles by default. We should only selectively remove focus styles when the polyfill is loaded, as suggested in the [focus-visible polyfill README](https://github.com/WICG/focus-visible#2-update-your-css).

```css
/*
  This will hide the focus indicator if the element receives focus via the mouse,
  but it will still show up on keyboard focus.
*/
.js-focus-visible :focus:not(.focus-visible) {
  outline: none;
}
```

We could do something similar with the native `:focus-visible` selector since both [Chrome and Firefox](https://caniuse.com/css-focus-visible) have support.

## Describe alternatives you've considered
Rely on education to solve this problem. However, education will not be 100% effective and missing focus styles will slip through the cracks.  Instead, we should provide an accessible default and educate how to use focus-visible to meet our design goals.

**Comment by blackfalcon** [comment]
There have been many discussions on this. Thanks for bringing this back, I will make this a priority to address.

**Comment by geoffrich** [comment]
Synced up with Jason and I'm going to take a first stab at a PR for this.

**Comment by littleninja** [comment]
> There have been many discussions on this.

Yup!: #47
