### ISSUE TITLE
SCSS helper for custom property fallbacks

### ISSUE THREAD

**Issue by littleninja** [AlaskaAirlines/WebCoreStyleSheets#64]
## Is your feature request related to a problem? Please describe.
Auro uses CSS custom properties and [a PostCSS plugin](https://auro.alaskaair.com/support/custom-properties#fallback-properties-at-scale) and CSS's cascading behavior to ensure colors are present. But--this does not cover cases where variables are unset as [I discovered working on auro-backtotop](https://github.com/AlaskaAirlines/auro-backtotop/commit/feae094a639c5a956edf4890e49fd3da033dff55#commitcomment-47566393). I'd like to see Auro core styles handle both: browsers without custom property support, and pages without or outdated Auro custom properties.

## Describe the solution you'd like
I think we could solve this with a function that accepts a variable name and returns the correct `var()` value.
```scss
@function auro-var ($name, $fallback:\$#{$name}) {
  @return var(--#{$name}, #{$fallback});
}
```

## Describe alternatives you've considered
Updating docs to explain why developers should probably start writing variables like this everywhere:
```scss
color: var(--auro-my-color, $auro-my-color);
```
- [Auro Design System: ShadyCSS](https://auro.alaskaair.com/support/shadycss)
- [Auro Design System: CSS Custom Properties](https://auro.alaskaair.com/support/custom-properties)

## Additional context

![screenshot of unstyled button background because variable was unset](https://user-images.githubusercontent.com/4391579/109212197-118fbe00-7764-11eb-9e60-6710a489c75f.png)

**Comment by littleninja** [comment]
I realized this SCSS syntax doesn't work, it will result in the literal string with the variable name instead of the variable's value. A SCSS map of design tokens would help.

Question on adding flap-map support: are adding a new file? Do you know of a way to append multiple transforms into a single file?

https://github.com/AlaskaAirlines/AuroDesignTokens/blob/34438540c6b72080092d6f07ce2c95036bc9596c/scripts/config.json#L34

**Comment by blackfalcon** [comment]
I don't want to lose sight of this. This issue is to be reviewed in combination with the work with https://github.com/AlaskaAirlines/WC-Generator/issues/66
