### ISSUE TITLE
WCSS: review .focus-visible selector

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/WebCoreStyleSheets#76]
# General Support Request

With the growing movement to the supported `:focus-visible` pseudo-class, the `.focus-visible` selector needs to be reviewed for relevancy. 

## Support request

The [current selector](https://alaskaairlines.github.io/WebCoreStyleSheets/#css-#{$scope}.focus-visible) was intended to be a utility class that could be appended to manual uses of the hyperlink, button, and tab. With the recent releases of support for `:focus-visible` we do not have support for this scenario as a utility class. 

## Possible Solution

1. Do we need support for this as a utility class? 
2. Should we deprecate the current utility class? 
3. ¯\_(ツ)_/¯

**Comment by braven112** [comment]
@blackfalcon Review this again.  We need to look at Safari.

**Comment by blackfalcon** [comment]
After further review of the state of `:focus-visible` and some of the inherent complexities of WCSS and Sass, there is nothing that can really or needs to be done at this time.

Please reference https://github.com/AlaskaAirlines/WebCoreStyleSheets/issues/105 for a carry forward of work to be done.
