### ISSUE TITLE
WCSS: AS Circular ligatures active in global styling

### ISSUE THREAD

**Issue by tombauer85** [AlaskaAirlines/WebCoreStyleSheets#80]
Per [AS brand guidelines (pg. 13)](https://static1.squarespace.com/static/5c58929990f904c2d00742d7/t/5ecd612fb6e5372e0e612fda/1590518396762/Alaska+Airlines+BrandGuidelines+2020.pdf), ligatures should not be active for the AS Circular font on AS.com. 

1. Go to [AS.com](https://www.alaskaair.com/)
2. View the CTA "Find flight deals now"
3. Observe that the ligature is active and most commonly occurs with the letter combination f + l.

Expected behavior:
No ligatures active for digital experiences on AS.com and MOW.

Screenshots

![As_MOW_ligature](https://user-images.githubusercontent.com/79945832/118316486-c015e600-b4ab-11eb-89a6-2b043a0b5366.png)
![AS_desktop_ligature](https://user-images.githubusercontent.com/79945832/118316565-d754d380-b4ab-11eb-8f8b-a7b39d3e0308.png)

Desktop:
 - Browser: All browsers

Smartphone:
  - MOW: All devices

**Comment by blackfalcon** [comment]
@tombauer85 thanks for submitting this issue, but I am afraid I have no real resource to correct this. This issue has to do with the font library and the Auro team has no control over that. 

When using [WCSS](https://github.com/AlaskaAirlines/WebCoreStyleSheets), the code for the web font is here https://github.com/AlaskaAirlines/WebCoreStyleSheets/blob/master/src/_fonts.scss. That being said, what individual teams are doing is not in our control. 

That being said, if you look at the page you are referencing, using the inspector you can add `letter-spacing: 0.1px` and that ligature is dropped. We _could_ add that to [WCSS](https://github.com/AlaskaAirlines/WebCoreStyleSheets) as a default, but that is not our decision, that needs to come from design. Not to mention, it feels a little hackie.

**Comment by blackfalcon** [comment]
With `letter-spacing: 0.1px` set at the page level. All type is affected by this. 

<img width="468" alt="Screen Shot 2021-05-14 at 1 53 04 PM" src="https://user-images.githubusercontent.com/181089/118329354-bb592e00-b4bb-11eb-97c3-a0c33cd1c7df.png">

**Comment by tombauer85** [comment]
@blackfalcon interesting, so we can't apply this code to the global styling? 

font-variant-ligatures: no-common-ligatures;

When I add this to the CSS under "body, html" it seems to render all text without ligatures.

<img width="1224" alt="Screen Shot 2021-05-14 at 1 55 16 PM" src="https://user-images.githubusercontent.com/79945832/118330816-c2cd0700-b4bc-11eb-9acc-7e4d8b71f5ce.png">

**Comment by blackfalcon** [comment]
Yeah, `font-variant-ligatures` would do the work and is not as hacky. Yeah, we do that 100!

**Comment by tombauer85** [comment]
Great, thanks! @blackfalcon

**Comment by tombauer85** [comment]
Hi @blackfalcon, just wanted to check in on this. It doesn't look like the ligature issue was ever fixed on the homepage. Was this added to the global styling? Could you please let me know if there is any action on the content production end to finally fix this issue?
<img width="1136" alt="Screen Shot 2021-08-17 at 11 07 25 AM" src="https://user-images.githubusercontent.com/79945832/129778383-24b5cc02-6e4b-4e9c-b45e-8c02273e3488.png">

**Comment by blackfalcon** [comment]
Hey @tombauer85 this update was released with v3.4.0. Can you confirm with the team as to what version of WCSS they are using? 

This was added to the [essentials](https://github.com/AlaskaAirlines/WebCoreStyleSheets/blob/master/src/_essentials.scss#L63) file, so please verify if that resource is being used.

**Comment by tombauer85** [comment]
Talked to Steven and Marnel about this, Content Enablement is working on getting the latest WCSS imported globally either this sprint or next. Thanks for your help!
