### ISSUE TITLE
WCSS: Full set of web-based fonts for Auro

### ISSUE THREAD

**Issue by KaylaBlyton1** [AlaskaAirlines/WebCoreStyleSheets#81]
[2015.10.22 - AS Circular Web.zip](https://github.com/AlaskaAirlines/WebCoreStyleSheets/files/6480761/2015.10.22.-.AS.Circular.Web.zip)
# General Support Request

Context: It was raised to my attention that developers are not utilizing the full AS Circular typeface. Instead, a couple weights are being used for a wide range of tokens. This results in coded components looking different from Figma documents. 

For example: heading-500-px-breakpoint-md shows up heavier than the medium weight in Figma. In addition, the "$" in the coded element does not have a strikethrough, but in Figma it does. This is due to a discrepancy of the font weight.

The ask: Update auro font tokens to represent the true weight and font in the AS Circular Webfont file. 

Note: I'm not listing this as a bug, because I believe this was an intentional decision that was made somewhere along the line. I recognize that this ask may be complex - please let me know how I can support and don't hesitate to reach out.

**Comment by blackfalcon** [comment]
Auro does not own the font files. These are distributed via content's CDN 
https://github.com/AlaskaAirlines/WebCoreStyleSheets/blob/master/src/_fonts.scss

Here is a link to the current Auro type support. https://auro.alaskaair.com/typography/overview

If there is to be a change, we need to discuss specifically what that change is and how this will affect that document. 

If there are differences between how a browser renders a font versus how Figma renders that same font and weight I would refer you to https://forum.figma.com/t/why-does-a-font-weight-in-figma-seem-lighter-than-the-same-weight-in-the-browser/2207

**Comment by KaylaBlyton1** [comment]
Thanks Dale. After reading through your links, this would fall under the category of your second link- changing the Auro type support page. 

The line at the top of the Auro typography page addresses what we'd like to change: "Using three distinct lighter-weights, we maintain a level consistency within our content hierarchy."

The problem as it stands is that designers are using a broader range of fonts weights than the 3 that are being used as the basis for all the weights. Developers use the corresponding weights in the coded experience, but they are not appearing one-to-one because the font is different. 

I will put some time on your calendar to discuss specifics, and invite a few other folks who can provide examples of what I am describing.

**Comment by blackfalcon** [comment]
Moving this issue back to the backlog and marking as blocked. Unable to move forward until there is a new design asset to review prior to any updates we can deliver. 

@KaylaBlyton1

**Comment by blackfalcon** [comment]
The issue of supporting additional web-based fonts has changed direction. We are now looking to support variable fonts. 

This will result in a new line of work, e.g. we need to convert the current primary font family to a variable font and this is not something we can do on our own. 

The work required is now out of the scope of this issue.
