### ISSUE TITLE
Generator: Mobile Demo view

### ISSUE THREAD

**Issue by braven112** [AlaskaAirlines/WebCoreStyleSheets#92]
## Is your feature request related to a problem? Please describe.

When making a component for mobile the current demo page has 3rem margin on the body.  Most pages on the site are either 15px or 1rem(16px).  Which makes it more difficult to verify the look on mobile.

## Describe the solution you'd like

I'd like to see the demo page match the rest of the site as much as possible.

Current
![image](https://user-images.githubusercontent.com/5118118/128577154-6fda740d-10a2-447f-bc7a-fed81355cfa8.png)

Ideal
![image](https://user-images.githubusercontent.com/5118118/128577241-14b4bc1f-af58-4ef9-9edf-8d0f48373cb9.png)

**Comment by blackfalcon** [comment]
This issue is directly related to the work addressed here https://github.com/AlaskaAirlines/WebCoreStyleSheets/pull/91/files#diff-40a26141a8c1859daeefe1d4dd3e26bf3b369a27ba192fe1df39aee073da9f6eR23-R31

https://github.com/AlaskaAirlines/WebCoreStyleSheets/issues/90
